Updates documentation for Principles and Environments
nulogy/design-system-old pull request #10
Opened 2018-07-16 19:11 UTC by nikola-nulogy

Also updates styling and the logo.

2018-07-16 19:37 UTC, theinterned requested changes
@nikola-nulogy looks good: I left a few comments that it would be good to address before merging

2018-07-16 19:37 UTC, theinterned commented on catalog/foundation/principles.md
> +## Adaptive Experience
Is the description missing here?

2018-07-16 19:37 UTC, theinterned commented on catalog/index.js
> +    //fontHeading: "'Rubik', serif",
I noticed these lines were commented out and restored them.

2018-07-16 19:37 UTC, theinterned commented on catalog/foundation/environments.md
> +<div><img src="/environments.png" /></div>
do we want this image to be responsive in any way? at least with a `width: 100%;`?

2018-07-16 19:37 UTC, theinterned commented on catalog/foundation/environments.md
> +<div><img src="/environments.png" /></div>
```css
width: 100%;
min-width: 500px;  // or whatever
```

Also, what is the div for?

2018-07-16 19:37 UTC, theinterned commented on catalog/foundation/environments.md
> +<div><img src="/environments.png" /></div>
@nikola-nulogy did you consider using the [Image speciman](https://docs.catalog.style/specimens/image)?

2018-07-19 12:03 UTC, nikola-nulogy commented on catalog/foundation/environments.md
> +<div><img src="/environments.png" /></div>
I didn't and probably should have. I guess this was me just playing around. I will have a look at image specimen and provide a proper implementation.

2018-07-19 12:10 UTC, nikola-nulogy commented on catalog/foundation/principles.md
> +## Adaptive Experience
We do not have properly written description for this one that's why it is not included.

2018-07-19 14:23 UTC, theinterned approved these changes

2018-07-19 14:23 UTC, merged